/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.tfl.ide.contentassist.antlr.internal.InternalTflParser;
import org.xtext.example.tfl.services.TflGrammarAccess;

public class TflParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TflGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TflGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTflSystemAccess().getGroup(), "rule__TflSystem__Group__0");
			builder.put(grammarAccess.getStopAccess().getGroup(), "rule__Stop__Group__0");
			builder.put(grammarAccess.getTransportAccess().getGroup(), "rule__Transport__Group__0");
			builder.put(grammarAccess.getRouteAccess().getGroup(), "rule__Route__Group__0");
			builder.put(grammarAccess.getDisruptionAccess().getGroup(), "rule__Disruption__Group__0");
			builder.put(grammarAccess.getREALAccess().getGroup(), "rule__REAL__Group__0");
			builder.put(grammarAccess.getTflSystemAccess().getStopsAssignment_0(), "rule__TflSystem__StopsAssignment_0");
			builder.put(grammarAccess.getTflSystemAccess().getTransportsAssignment_1(), "rule__TflSystem__TransportsAssignment_1");
			builder.put(grammarAccess.getTflSystemAccess().getDisruptionsAssignment_2(), "rule__TflSystem__DisruptionsAssignment_2");
			builder.put(grammarAccess.getStopAccess().getNameAssignment_1(), "rule__Stop__NameAssignment_1");
			builder.put(grammarAccess.getTransportAccess().getNameAssignment_1(), "rule__Transport__NameAssignment_1");
			builder.put(grammarAccess.getTransportAccess().getCapacityAssignment_3(), "rule__Transport__CapacityAssignment_3");
			builder.put(grammarAccess.getTransportAccess().getSpeedAssignment_5(), "rule__Transport__SpeedAssignment_5");
			builder.put(grammarAccess.getTransportAccess().getRoutesAssignment_9(), "rule__Transport__RoutesAssignment_9");
			builder.put(grammarAccess.getTransportAccess().getPeakAssignment_14(), "rule__Transport__PeakAssignment_14");
			builder.put(grammarAccess.getTransportAccess().getNonPeakAssignment_16(), "rule__Transport__NonPeakAssignment_16");
			builder.put(grammarAccess.getRouteAccess().getStartAssignment_0(), "rule__Route__StartAssignment_0");
			builder.put(grammarAccess.getRouteAccess().getEndAssignment_2(), "rule__Route__EndAssignment_2");
			builder.put(grammarAccess.getRouteAccess().getDurationAssignment_4(), "rule__Route__DurationAssignment_4");
			builder.put(grammarAccess.getDisruptionAccess().getNameAssignment_1(), "rule__Disruption__NameAssignment_1");
			builder.put(grammarAccess.getDisruptionAccess().getTransportAssignment_3(), "rule__Disruption__TransportAssignment_3");
			builder.put(grammarAccess.getDisruptionAccess().getStopAssignment_5(), "rule__Disruption__StopAssignment_5");
			builder.put(grammarAccess.getDisruptionAccess().getDurationAssignment_7(), "rule__Disruption__DurationAssignment_7");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TflGrammarAccess grammarAccess;

	@Override
	protected InternalTflParser createParser() {
		InternalTflParser result = new InternalTflParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TflGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TflGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
