/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.tfl.ui.internal.TflActivator;

public class TflUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TflActivator.getInstance().getInjector("org.xtext.example.tfl.Tfl");
	}

}
