/*
 * generated by Xtext 2.37.0
 */
grammar InternalTfl;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package org.xtext.example.tfl.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package org.xtext.example.tfl.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import org.xtext.example.tfl.services.TflGrammarAccess;

}
@parser::members {
	private TflGrammarAccess grammarAccess;

	public void setGrammarAccess(TflGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleTflSystem
entryRuleTflSystem
:
{ before(grammarAccess.getTflSystemRule()); }
	 ruleTflSystem
{ after(grammarAccess.getTflSystemRule()); } 
	 EOF 
;

// Rule TflSystem
ruleTflSystem 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getTflSystemAccess().getGroup()); }
		(rule__TflSystem__Group__0)
		{ after(grammarAccess.getTflSystemAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleStop
entryRuleStop
:
{ before(grammarAccess.getStopRule()); }
	 ruleStop
{ after(grammarAccess.getStopRule()); } 
	 EOF 
;

// Rule Stop
ruleStop 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getStopAccess().getGroup()); }
		(rule__Stop__Group__0)
		{ after(grammarAccess.getStopAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleTransport
entryRuleTransport
:
{ before(grammarAccess.getTransportRule()); }
	 ruleTransport
{ after(grammarAccess.getTransportRule()); } 
	 EOF 
;

// Rule Transport
ruleTransport 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getTransportAccess().getGroup()); }
		(rule__Transport__Group__0)
		{ after(grammarAccess.getTransportAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleRoute
entryRuleRoute
:
{ before(grammarAccess.getRouteRule()); }
	 ruleRoute
{ after(grammarAccess.getRouteRule()); } 
	 EOF 
;

// Rule Route
ruleRoute 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getRouteAccess().getGroup()); }
		(rule__Route__Group__0)
		{ after(grammarAccess.getRouteAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleDisruption
entryRuleDisruption
:
{ before(grammarAccess.getDisruptionRule()); }
	 ruleDisruption
{ after(grammarAccess.getDisruptionRule()); } 
	 EOF 
;

// Rule Disruption
ruleDisruption 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getDisruptionAccess().getGroup()); }
		(rule__Disruption__Group__0)
		{ after(grammarAccess.getDisruptionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleREAL
entryRuleREAL
@init { 
	HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
}
:
{ before(grammarAccess.getREALRule()); }
	 ruleREAL
{ after(grammarAccess.getREALRule()); } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule REAL
ruleREAL 
	@init {
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getREALAccess().getGroup()); }
		(rule__REAL__Group__0)
		{ after(grammarAccess.getREALAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
	myHiddenTokenState.restore();
}

rule__TflSystem__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TflSystem__Group__0__Impl
	rule__TflSystem__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__TflSystem__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTflSystemAccess().getStopsAssignment_0()); }
	(rule__TflSystem__StopsAssignment_0)*
	{ after(grammarAccess.getTflSystemAccess().getStopsAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TflSystem__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TflSystem__Group__1__Impl
	rule__TflSystem__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__TflSystem__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTflSystemAccess().getTransportsAssignment_1()); }
	(rule__TflSystem__TransportsAssignment_1)*
	{ after(grammarAccess.getTflSystemAccess().getTransportsAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TflSystem__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TflSystem__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__TflSystem__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTflSystemAccess().getDisruptionsAssignment_2()); }
	(rule__TflSystem__DisruptionsAssignment_2)*
	{ after(grammarAccess.getTflSystemAccess().getDisruptionsAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Stop__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Stop__Group__0__Impl
	rule__Stop__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Stop__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getStopAccess().getStopKeyword_0()); }
	'stop'
	{ after(grammarAccess.getStopAccess().getStopKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Stop__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Stop__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Stop__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getStopAccess().getNameAssignment_1()); }
	(rule__Stop__NameAssignment_1)
	{ after(grammarAccess.getStopAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Transport__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__0__Impl
	rule__Transport__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getTransportKeyword_0()); }
	'transport'
	{ after(grammarAccess.getTransportAccess().getTransportKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__1__Impl
	rule__Transport__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getNameAssignment_1()); }
	(rule__Transport__NameAssignment_1)
	{ after(grammarAccess.getTransportAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__2__Impl
	rule__Transport__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getCapacityKeyword_2()); }
	'capacity'
	{ after(grammarAccess.getTransportAccess().getCapacityKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__3__Impl
	rule__Transport__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getCapacityAssignment_3()); }
	(rule__Transport__CapacityAssignment_3)
	{ after(grammarAccess.getTransportAccess().getCapacityAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__4__Impl
	rule__Transport__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getSpeedKeyword_4()); }
	'speed'
	{ after(grammarAccess.getTransportAccess().getSpeedKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__5__Impl
	rule__Transport__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getSpeedAssignment_5()); }
	(rule__Transport__SpeedAssignment_5)
	{ after(grammarAccess.getTransportAccess().getSpeedAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__6__Impl
	rule__Transport__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getKmphKeyword_6()); }
	'kmph'
	{ after(grammarAccess.getTransportAccess().getKmphKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__7__Impl
	rule__Transport__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getRoutesKeyword_7()); }
	'routes'
	{ after(grammarAccess.getTransportAccess().getRoutesKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__8__Impl
	rule__Transport__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getLeftCurlyBracketKeyword_8()); }
	'{'
	{ after(grammarAccess.getTransportAccess().getLeftCurlyBracketKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__9__Impl
	rule__Transport__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getRoutesAssignment_9()); }
	(rule__Transport__RoutesAssignment_9)*
	{ after(grammarAccess.getTransportAccess().getRoutesAssignment_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__10__Impl
	rule__Transport__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getRightCurlyBracketKeyword_10()); }
	'}'
	{ after(grammarAccess.getTransportAccess().getRightCurlyBracketKeyword_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__11__Impl
	rule__Transport__Group__12
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getPassengersKeyword_11()); }
	'passengers'
	{ after(grammarAccess.getTransportAccess().getPassengersKeyword_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__12
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__12__Impl
	rule__Transport__Group__13
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__12__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getLeftCurlyBracketKeyword_12()); }
	'{'
	{ after(grammarAccess.getTransportAccess().getLeftCurlyBracketKeyword_12()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__13
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__13__Impl
	rule__Transport__Group__14
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__13__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getPeakKeyword_13()); }
	'peak'
	{ after(grammarAccess.getTransportAccess().getPeakKeyword_13()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__14
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__14__Impl
	rule__Transport__Group__15
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__14__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getPeakAssignment_14()); }
	(rule__Transport__PeakAssignment_14)
	{ after(grammarAccess.getTransportAccess().getPeakAssignment_14()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__15
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__15__Impl
	rule__Transport__Group__16
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__15__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getNonpeakKeyword_15()); }
	'nonpeak'
	{ after(grammarAccess.getTransportAccess().getNonpeakKeyword_15()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__16
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__16__Impl
	rule__Transport__Group__17
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__16__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getNonPeakAssignment_16()); }
	(rule__Transport__NonPeakAssignment_16)
	{ after(grammarAccess.getTransportAccess().getNonPeakAssignment_16()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__17
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Transport__Group__17__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__Group__17__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTransportAccess().getRightCurlyBracketKeyword_17()); }
	'}'
	{ after(grammarAccess.getTransportAccess().getRightCurlyBracketKeyword_17()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Route__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Route__Group__0__Impl
	rule__Route__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRouteAccess().getStartAssignment_0()); }
	(rule__Route__StartAssignment_0)
	{ after(grammarAccess.getRouteAccess().getStartAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Route__Group__1__Impl
	rule__Route__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRouteAccess().getHyphenMinusGreaterThanSignKeyword_1()); }
	'->'
	{ after(grammarAccess.getRouteAccess().getHyphenMinusGreaterThanSignKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Route__Group__2__Impl
	rule__Route__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRouteAccess().getEndAssignment_2()); }
	(rule__Route__EndAssignment_2)
	{ after(grammarAccess.getRouteAccess().getEndAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Route__Group__3__Impl
	rule__Route__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRouteAccess().getInKeyword_3()); }
	'in'
	{ after(grammarAccess.getRouteAccess().getInKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Route__Group__4__Impl
	rule__Route__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRouteAccess().getDurationAssignment_4()); }
	(rule__Route__DurationAssignment_4)
	{ after(grammarAccess.getRouteAccess().getDurationAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Route__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRouteAccess().getMinKeyword_5()); }
	'min'
	{ after(grammarAccess.getRouteAccess().getMinKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Disruption__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Disruption__Group__0__Impl
	rule__Disruption__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDisruptionAccess().getDisruptionKeyword_0()); }
	'disruption'
	{ after(grammarAccess.getDisruptionAccess().getDisruptionKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Disruption__Group__1__Impl
	rule__Disruption__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDisruptionAccess().getNameAssignment_1()); }
	(rule__Disruption__NameAssignment_1)
	{ after(grammarAccess.getDisruptionAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Disruption__Group__2__Impl
	rule__Disruption__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDisruptionAccess().getAffectsKeyword_2()); }
	'affects'
	{ after(grammarAccess.getDisruptionAccess().getAffectsKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Disruption__Group__3__Impl
	rule__Disruption__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDisruptionAccess().getTransportAssignment_3()); }
	(rule__Disruption__TransportAssignment_3)
	{ after(grammarAccess.getDisruptionAccess().getTransportAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Disruption__Group__4__Impl
	rule__Disruption__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDisruptionAccess().getAtKeyword_4()); }
	'at'
	{ after(grammarAccess.getDisruptionAccess().getAtKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Disruption__Group__5__Impl
	rule__Disruption__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDisruptionAccess().getStopAssignment_5()); }
	(rule__Disruption__StopAssignment_5)
	{ after(grammarAccess.getDisruptionAccess().getStopAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Disruption__Group__6__Impl
	rule__Disruption__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDisruptionAccess().getDurationKeyword_6()); }
	'duration'
	{ after(grammarAccess.getDisruptionAccess().getDurationKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Disruption__Group__7__Impl
	rule__Disruption__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDisruptionAccess().getDurationAssignment_7()); }
	(rule__Disruption__DurationAssignment_7)
	{ after(grammarAccess.getDisruptionAccess().getDurationAssignment_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Disruption__Group__8__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDisruptionAccess().getMinKeyword_8()); }
	'min'
	{ after(grammarAccess.getDisruptionAccess().getMinKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__REAL__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__REAL__Group__0__Impl
	rule__REAL__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__REAL__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getREALAccess().getINTTerminalRuleCall_0()); }
	(RULE_INT)?
	{ after(grammarAccess.getREALAccess().getINTTerminalRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__REAL__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__REAL__Group__1__Impl
	rule__REAL__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__REAL__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getREALAccess().getFullStopKeyword_1()); }
	'.'
	{ after(grammarAccess.getREALAccess().getFullStopKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__REAL__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__REAL__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__REAL__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getREALAccess().getINTTerminalRuleCall_2()); }
	RULE_INT
	{ after(grammarAccess.getREALAccess().getINTTerminalRuleCall_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__TflSystem__StopsAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTflSystemAccess().getStopsStopParserRuleCall_0_0()); }
		ruleStop
		{ after(grammarAccess.getTflSystemAccess().getStopsStopParserRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__TflSystem__TransportsAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTflSystemAccess().getTransportsTransportParserRuleCall_1_0()); }
		ruleTransport
		{ after(grammarAccess.getTflSystemAccess().getTransportsTransportParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__TflSystem__DisruptionsAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTflSystemAccess().getDisruptionsDisruptionParserRuleCall_2_0()); }
		ruleDisruption
		{ after(grammarAccess.getTflSystemAccess().getDisruptionsDisruptionParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Stop__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getStopAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getStopAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTransportAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getTransportAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__CapacityAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTransportAccess().getCapacityINTTerminalRuleCall_3_0()); }
		RULE_INT
		{ after(grammarAccess.getTransportAccess().getCapacityINTTerminalRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__SpeedAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTransportAccess().getSpeedREALParserRuleCall_5_0()); }
		ruleREAL
		{ after(grammarAccess.getTransportAccess().getSpeedREALParserRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__RoutesAssignment_9
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTransportAccess().getRoutesRouteParserRuleCall_9_0()); }
		ruleRoute
		{ after(grammarAccess.getTransportAccess().getRoutesRouteParserRuleCall_9_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__PeakAssignment_14
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTransportAccess().getPeakINTTerminalRuleCall_14_0()); }
		RULE_INT
		{ after(grammarAccess.getTransportAccess().getPeakINTTerminalRuleCall_14_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Transport__NonPeakAssignment_16
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTransportAccess().getNonPeakINTTerminalRuleCall_16_0()); }
		RULE_INT
		{ after(grammarAccess.getTransportAccess().getNonPeakINTTerminalRuleCall_16_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__StartAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRouteAccess().getStartIDTerminalRuleCall_0_0()); }
		RULE_ID
		{ after(grammarAccess.getRouteAccess().getStartIDTerminalRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__EndAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRouteAccess().getEndIDTerminalRuleCall_2_0()); }
		RULE_ID
		{ after(grammarAccess.getRouteAccess().getEndIDTerminalRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Route__DurationAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRouteAccess().getDurationINTTerminalRuleCall_4_0()); }
		RULE_INT
		{ after(grammarAccess.getRouteAccess().getDurationINTTerminalRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDisruptionAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getDisruptionAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__TransportAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDisruptionAccess().getTransportTransportCrossReference_3_0()); }
		(
			{ before(grammarAccess.getDisruptionAccess().getTransportTransportIDTerminalRuleCall_3_0_1()); }
			RULE_ID
			{ after(grammarAccess.getDisruptionAccess().getTransportTransportIDTerminalRuleCall_3_0_1()); }
		)
		{ after(grammarAccess.getDisruptionAccess().getTransportTransportCrossReference_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__StopAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDisruptionAccess().getStopStopCrossReference_5_0()); }
		(
			{ before(grammarAccess.getDisruptionAccess().getStopStopIDTerminalRuleCall_5_0_1()); }
			RULE_ID
			{ after(grammarAccess.getDisruptionAccess().getStopStopIDTerminalRuleCall_5_0_1()); }
		)
		{ after(grammarAccess.getDisruptionAccess().getStopStopCrossReference_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Disruption__DurationAssignment_7
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDisruptionAccess().getDurationINTTerminalRuleCall_7_0()); }
		RULE_INT
		{ after(grammarAccess.getDisruptionAccess().getDurationINTTerminalRuleCall_7_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
