/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.validation;

import java.util.Objects;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;
import org.xtext.example.tfl.tfl.Disruption;
import org.xtext.example.tfl.tfl.Route;
import org.xtext.example.tfl.tfl.Stop;
import org.xtext.example.tfl.tfl.TflPackage;
import org.xtext.example.tfl.tfl.TflSystem;
import org.xtext.example.tfl.tfl.Transport;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TflValidator extends AbstractTflValidator {
  public static final String INVALID_STOP_NAME = "invalidStopName";

  public static final String UNUSED_STOP = "unusedStop";

  public static final String DUPLICATE_DISRUPTION = "duplicateDisruption";

  @Check
  public void checkStopName(final Stop stop) {
    boolean _isLowerCase = Character.isLowerCase(stop.getName().charAt(0));
    if (_isLowerCase) {
      this.warning("Stop name should start with an upper-case character", stop, 
        TflPackage.Literals.STOP__NAME, TflValidator.INVALID_STOP_NAME);
    }
  }

  @Check(CheckType.NORMAL)
  public void checkIfStopIsUsed(final TflSystem system) {
    EList<Stop> _stops = system.getStops();
    for (final Stop stop : _stops) {
      boolean _isStopReferenced = this.isStopReferenced(stop, system.getTransports(), system.getDisruptions());
      boolean _not = (!_isStopReferenced);
      if (_not) {
        this.warning("This stop is unused", stop, 
          TflPackage.Literals.STOP__NAME, TflValidator.UNUSED_STOP);
      }
    }
  }

  public boolean isStopReferenced(final Stop stop, final EList<Transport> transports, final EList<Disruption> disruptions) {
    for (final Transport transport : transports) {
      EList<Route> _routes = transport.getRoutes();
      for (final Route route : _routes) {
        if ((route.getStart().equals(stop.getName()) || route.getEnd().equals(stop.getName()))) {
          return true;
        }
      }
    }
    for (final Disruption disruption : disruptions) {
      Stop _stop = disruption.getStop();
      boolean _equals = Objects.equals(_stop, stop);
      if (_equals) {
        return true;
      }
    }
    return false;
  }
}
