/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.tfl.TflRuntimeModule;
import org.xtext.example.tfl.TflStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TflIdeSetup extends TflStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TflRuntimeModule(), new TflIdeModule()));
	}
	
}
