/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TflUiModule extends AbstractTflUiModule {

	public TflUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
