/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TflGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class TflSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.tfl.Tfl.TflSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStopsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cStopsStopParserRuleCall_0_0 = (RuleCall)cStopsAssignment_0.eContents().get(0);
		private final Assignment cTransportsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTransportsTransportParserRuleCall_1_0 = (RuleCall)cTransportsAssignment_1.eContents().get(0);
		private final Assignment cDisruptionsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDisruptionsDisruptionParserRuleCall_2_0 = (RuleCall)cDisruptionsAssignment_2.eContents().get(0);
		
		//// We define the stops, different transports and disruptions on any transport
		//TflSystem:
		//    stops+=Stop*
		//    transports+=Transport*
		//    disruptions+=Disruption*;
		@Override public ParserRule getRule() { return rule; }
		
		//stops+=Stop*
		//transports+=Transport*
		//disruptions+=Disruption*
		public Group getGroup() { return cGroup; }
		
		//stops+=Stop*
		public Assignment getStopsAssignment_0() { return cStopsAssignment_0; }
		
		//Stop
		public RuleCall getStopsStopParserRuleCall_0_0() { return cStopsStopParserRuleCall_0_0; }
		
		//transports+=Transport*
		public Assignment getTransportsAssignment_1() { return cTransportsAssignment_1; }
		
		//Transport
		public RuleCall getTransportsTransportParserRuleCall_1_0() { return cTransportsTransportParserRuleCall_1_0; }
		
		//disruptions+=Disruption*
		public Assignment getDisruptionsAssignment_2() { return cDisruptionsAssignment_2; }
		
		//Disruption
		public RuleCall getDisruptionsDisruptionParserRuleCall_2_0() { return cDisruptionsDisruptionParserRuleCall_2_0; }
	}
	public class StopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.tfl.Tfl.Stop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Stop:
		//    'stop' name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'stop' name=ID
		public Group getGroup() { return cGroup; }
		
		//'stop'
		public Keyword getStopKeyword_0() { return cStopKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class TransportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.tfl.Tfl.Transport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cCapacityKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCapacityAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCapacityINTTerminalRuleCall_3_0 = (RuleCall)cCapacityAssignment_3.eContents().get(0);
		private final Keyword cSpeedKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSpeedAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSpeedREALParserRuleCall_5_0 = (RuleCall)cSpeedAssignment_5.eContents().get(0);
		private final Keyword cKmphKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRoutesKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cRoutesAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cRoutesRouteParserRuleCall_9_0 = (RuleCall)cRoutesAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cPassengersKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cLeftCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cPeakKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cPeakAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cPeakINTTerminalRuleCall_14_0 = (RuleCall)cPeakAssignment_14.eContents().get(0);
		private final Keyword cNonpeakKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cNonPeakAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cNonPeakINTTerminalRuleCall_16_0 = (RuleCall)cNonPeakAssignment_16.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		
		//// capacity and passengers will be used to calculate fare late
		//Transport:
		//    'transport' name=ID
		//    'capacity' capacity=INT
		//    'speed' speed=REAL 'kmph'
		//    'routes' '{' routes+=Route* '}'
		//    'passengers' '{'
		//        'peak' peak=INT
		//        'nonpeak' nonPeak=INT
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'transport' name=ID
		//'capacity' capacity=INT
		//'speed' speed=REAL 'kmph'
		//'routes' '{' routes+=Route* '}'
		//'passengers' '{'
		//    'peak' peak=INT
		//    'nonpeak' nonPeak=INT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'transport'
		public Keyword getTransportKeyword_0() { return cTransportKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'capacity'
		public Keyword getCapacityKeyword_2() { return cCapacityKeyword_2; }
		
		//capacity=INT
		public Assignment getCapacityAssignment_3() { return cCapacityAssignment_3; }
		
		//INT
		public RuleCall getCapacityINTTerminalRuleCall_3_0() { return cCapacityINTTerminalRuleCall_3_0; }
		
		//'speed'
		public Keyword getSpeedKeyword_4() { return cSpeedKeyword_4; }
		
		//speed=REAL
		public Assignment getSpeedAssignment_5() { return cSpeedAssignment_5; }
		
		//REAL
		public RuleCall getSpeedREALParserRuleCall_5_0() { return cSpeedREALParserRuleCall_5_0; }
		
		//'kmph'
		public Keyword getKmphKeyword_6() { return cKmphKeyword_6; }
		
		//'routes'
		public Keyword getRoutesKeyword_7() { return cRoutesKeyword_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//routes+=Route*
		public Assignment getRoutesAssignment_9() { return cRoutesAssignment_9; }
		
		//Route
		public RuleCall getRoutesRouteParserRuleCall_9_0() { return cRoutesRouteParserRuleCall_9_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
		
		//'passengers'
		public Keyword getPassengersKeyword_11() { return cPassengersKeyword_11; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12() { return cLeftCurlyBracketKeyword_12; }
		
		//'peak'
		public Keyword getPeakKeyword_13() { return cPeakKeyword_13; }
		
		//peak=INT
		public Assignment getPeakAssignment_14() { return cPeakAssignment_14; }
		
		//INT
		public RuleCall getPeakINTTerminalRuleCall_14_0() { return cPeakINTTerminalRuleCall_14_0; }
		
		//'nonpeak'
		public Keyword getNonpeakKeyword_15() { return cNonpeakKeyword_15; }
		
		//nonPeak=INT
		public Assignment getNonPeakAssignment_16() { return cNonPeakAssignment_16; }
		
		//INT
		public RuleCall getNonPeakINTTerminalRuleCall_16_0() { return cNonPeakINTTerminalRuleCall_16_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
	}
	public class RouteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.tfl.Tfl.Route");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStartAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cStartIDTerminalRuleCall_0_0 = (RuleCall)cStartAssignment_0.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cEndAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cEndIDTerminalRuleCall_2_0 = (RuleCall)cEndAssignment_2.eContents().get(0);
		private final Keyword cInKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDurationAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDurationINTTerminalRuleCall_4_0 = (RuleCall)cDurationAssignment_4.eContents().get(0);
		private final Keyword cMinKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//// Considering only start and end destination of the transport
		//Route:
		//    start=ID '->' end=ID 'in' duration=INT 'min';
		@Override public ParserRule getRule() { return rule; }
		
		//start=ID '->' end=ID 'in' duration=INT 'min'
		public Group getGroup() { return cGroup; }
		
		//start=ID
		public Assignment getStartAssignment_0() { return cStartAssignment_0; }
		
		//ID
		public RuleCall getStartIDTerminalRuleCall_0_0() { return cStartIDTerminalRuleCall_0_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_1() { return cHyphenMinusGreaterThanSignKeyword_1; }
		
		//end=ID
		public Assignment getEndAssignment_2() { return cEndAssignment_2; }
		
		//ID
		public RuleCall getEndIDTerminalRuleCall_2_0() { return cEndIDTerminalRuleCall_2_0; }
		
		//'in'
		public Keyword getInKeyword_3() { return cInKeyword_3; }
		
		//duration=INT
		public Assignment getDurationAssignment_4() { return cDurationAssignment_4; }
		
		//INT
		public RuleCall getDurationINTTerminalRuleCall_4_0() { return cDurationINTTerminalRuleCall_4_0; }
		
		//'min'
		public Keyword getMinKeyword_5() { return cMinKeyword_5; }
	}
	public class DisruptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.tfl.Tfl.Disruption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDisruptionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cAffectsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTransportAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cTransportTransportCrossReference_3_0 = (CrossReference)cTransportAssignment_3.eContents().get(0);
		private final RuleCall cTransportTransportIDTerminalRuleCall_3_0_1 = (RuleCall)cTransportTransportCrossReference_3_0.eContents().get(1);
		private final Keyword cAtKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStopAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cStopStopCrossReference_5_0 = (CrossReference)cStopAssignment_5.eContents().get(0);
		private final RuleCall cStopStopIDTerminalRuleCall_5_0_1 = (RuleCall)cStopStopCrossReference_5_0.eContents().get(1);
		private final Keyword cDurationKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDurationAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cDurationINTTerminalRuleCall_7_0 = (RuleCall)cDurationAssignment_7.eContents().get(0);
		private final Keyword cMinKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//// Disruption adds delays to the routes with this stop as start
		//Disruption:
		//    'disruption' name=ID
		//    'affects' transport=[Transport]
		//    'at' stop=[Stop]
		//    'duration' duration=INT 'min';
		@Override public ParserRule getRule() { return rule; }
		
		//'disruption' name=ID
		//'affects' transport=[Transport]
		//'at' stop=[Stop]
		//'duration' duration=INT 'min'
		public Group getGroup() { return cGroup; }
		
		//'disruption'
		public Keyword getDisruptionKeyword_0() { return cDisruptionKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'affects'
		public Keyword getAffectsKeyword_2() { return cAffectsKeyword_2; }
		
		//transport=[Transport]
		public Assignment getTransportAssignment_3() { return cTransportAssignment_3; }
		
		//[Transport]
		public CrossReference getTransportTransportCrossReference_3_0() { return cTransportTransportCrossReference_3_0; }
		
		//ID
		public RuleCall getTransportTransportIDTerminalRuleCall_3_0_1() { return cTransportTransportIDTerminalRuleCall_3_0_1; }
		
		//'at'
		public Keyword getAtKeyword_4() { return cAtKeyword_4; }
		
		//stop=[Stop]
		public Assignment getStopAssignment_5() { return cStopAssignment_5; }
		
		//[Stop]
		public CrossReference getStopStopCrossReference_5_0() { return cStopStopCrossReference_5_0; }
		
		//ID
		public RuleCall getStopStopIDTerminalRuleCall_5_0_1() { return cStopStopIDTerminalRuleCall_5_0_1; }
		
		//'duration'
		public Keyword getDurationKeyword_6() { return cDurationKeyword_6; }
		
		//duration=INT
		public Assignment getDurationAssignment_7() { return cDurationAssignment_7; }
		
		//INT
		public RuleCall getDurationINTTerminalRuleCall_7_0() { return cDurationINTTerminalRuleCall_7_0; }
		
		//'min'
		public Keyword getMinKeyword_8() { return cMinKeyword_8; }
	}
	public class REALElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.tfl.Tfl.REAL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//REAL returns ecore::EFloat hidden():
		//    INT? "." INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//INT? "." INT
		public Group getGroup() { return cGroup; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//"."
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	
	
	private final TflSystemElements pTflSystem;
	private final StopElements pStop;
	private final TransportElements pTransport;
	private final RouteElements pRoute;
	private final DisruptionElements pDisruption;
	private final REALElements pREAL;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TflGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTflSystem = new TflSystemElements();
		this.pStop = new StopElements();
		this.pTransport = new TransportElements();
		this.pRoute = new RouteElements();
		this.pDisruption = new DisruptionElements();
		this.pREAL = new REALElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.tfl.Tfl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//// We define the stops, different transports and disruptions on any transport
	//TflSystem:
	//    stops+=Stop*
	//    transports+=Transport*
	//    disruptions+=Disruption*;
	public TflSystemElements getTflSystemAccess() {
		return pTflSystem;
	}
	
	public ParserRule getTflSystemRule() {
		return getTflSystemAccess().getRule();
	}
	
	//Stop:
	//    'stop' name=ID;
	public StopElements getStopAccess() {
		return pStop;
	}
	
	public ParserRule getStopRule() {
		return getStopAccess().getRule();
	}
	
	//// capacity and passengers will be used to calculate fare late
	//Transport:
	//    'transport' name=ID
	//    'capacity' capacity=INT
	//    'speed' speed=REAL 'kmph'
	//    'routes' '{' routes+=Route* '}'
	//    'passengers' '{'
	//        'peak' peak=INT
	//        'nonpeak' nonPeak=INT
	//    '}';
	public TransportElements getTransportAccess() {
		return pTransport;
	}
	
	public ParserRule getTransportRule() {
		return getTransportAccess().getRule();
	}
	
	//// Considering only start and end destination of the transport
	//Route:
	//    start=ID '->' end=ID 'in' duration=INT 'min';
	public RouteElements getRouteAccess() {
		return pRoute;
	}
	
	public ParserRule getRouteRule() {
		return getRouteAccess().getRule();
	}
	
	//// Disruption adds delays to the routes with this stop as start
	//Disruption:
	//    'disruption' name=ID
	//    'affects' transport=[Transport]
	//    'at' stop=[Stop]
	//    'duration' duration=INT 'min';
	public DisruptionElements getDisruptionAccess() {
		return pDisruption;
	}
	
	public ParserRule getDisruptionRule() {
		return getDisruptionAccess().getRule();
	}
	
	//REAL returns ecore::EFloat hidden():
	//    INT? "." INT
	//;
	public REALElements getREALAccess() {
		return pREAL;
	}
	
	public ParserRule getREALRule() {
		return getREALAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
