grammar org.xtext.example.tfl.Tfl with org.eclipse.xtext.common.Terminals

generate tfl "http://www.xtext.org/example/tfl/Tfl"

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

// We define the stops, different transports and disruptions on any transport
TflSystem:
    stops+=Stop*
    transports+=Transport*
    disruptions+=Disruption*;
    
Stop:
    'stop' name=ID;

// capacity and passengers will be used to calculate fare late
Transport:
    'transport' name=ID 
    'capacity' capacity=INT 
    'speed' speed=REAL 'kmph' 
    'routes' '{' routes+=Route* '}' 
    'passengers' '{' 
        'peak' peak=INT 
        'nonpeak' nonPeak=INT 
    '}';

// Considering only start and end destination of the transport
Route:
    start=ID '->' end=ID 'in' duration=INT 'min';

// Disruption adds delays to the routes with this stop as start
Disruption:
    'disruption' name=ID 
    'affects' transport=[Transport] 
    'at' stop=[Stop] 
    'duration' duration=INT 'min';

REAL returns ecore::EFloat hidden():
	INT? "." INT
;
