/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TflStandaloneSetup extends TflStandaloneSetupGenerated {

	public static void doSetup() {
		new TflStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
