/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.tfl.ui.internal.TflActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TflExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TflActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TflActivator activator = TflActivator.getInstance();
		return activator != null ? activator.getInjector(TflActivator.ORG_XTEXT_EXAMPLE_TFL_TFL) : null;
	}

}
