/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.tfl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Disruption</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tfl.tfl.Disruption#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.Disruption#getTransport <em>Transport</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.Disruption#getStop <em>Stop</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.Disruption#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.tfl.tfl.TflPackage#getDisruption()
 * @model
 * @generated
 */
public interface Disruption extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.tfl.tfl.TflPackage#getDisruption_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.tfl.tfl.Disruption#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Transport</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transport</em>' reference.
   * @see #setTransport(Transport)
   * @see org.xtext.example.tfl.tfl.TflPackage#getDisruption_Transport()
   * @model
   * @generated
   */
  Transport getTransport();

  /**
   * Sets the value of the '{@link org.xtext.example.tfl.tfl.Disruption#getTransport <em>Transport</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transport</em>' reference.
   * @see #getTransport()
   * @generated
   */
  void setTransport(Transport value);

  /**
   * Returns the value of the '<em><b>Stop</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stop</em>' reference.
   * @see #setStop(Stop)
   * @see org.xtext.example.tfl.tfl.TflPackage#getDisruption_Stop()
   * @model
   * @generated
   */
  Stop getStop();

  /**
   * Sets the value of the '{@link org.xtext.example.tfl.tfl.Disruption#getStop <em>Stop</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stop</em>' reference.
   * @see #getStop()
   * @generated
   */
  void setStop(Stop value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(int)
   * @see org.xtext.example.tfl.tfl.TflPackage#getDisruption_Duration()
   * @model
   * @generated
   */
  int getDuration();

  /**
   * Sets the value of the '{@link org.xtext.example.tfl.tfl.Disruption#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(int value);

} // Disruption
