/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.tfl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.tfl.tfl.TflFactory
 * @model kind="package"
 * @generated
 */
public interface TflPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tfl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/tfl/Tfl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tfl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TflPackage eINSTANCE = org.xtext.example.tfl.tfl.impl.TflPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.tfl.tfl.impl.TflSystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.tfl.tfl.impl.TflSystemImpl
   * @see org.xtext.example.tfl.tfl.impl.TflPackageImpl#getTflSystem()
   * @generated
   */
  int TFL_SYSTEM = 0;

  /**
   * The feature id for the '<em><b>Stops</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TFL_SYSTEM__STOPS = 0;

  /**
   * The feature id for the '<em><b>Transports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TFL_SYSTEM__TRANSPORTS = 1;

  /**
   * The feature id for the '<em><b>Disruptions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TFL_SYSTEM__DISRUPTIONS = 2;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TFL_SYSTEM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.tfl.tfl.impl.StopImpl <em>Stop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.tfl.tfl.impl.StopImpl
   * @see org.xtext.example.tfl.tfl.impl.TflPackageImpl#getStop()
   * @generated
   */
  int STOP = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP__NAME = 0;

  /**
   * The number of structural features of the '<em>Stop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.tfl.tfl.impl.TransportImpl <em>Transport</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.tfl.tfl.impl.TransportImpl
   * @see org.xtext.example.tfl.tfl.impl.TflPackageImpl#getTransport()
   * @generated
   */
  int TRANSPORT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSPORT__NAME = 0;

  /**
   * The feature id for the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSPORT__CAPACITY = 1;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSPORT__SPEED = 2;

  /**
   * The feature id for the '<em><b>Routes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSPORT__ROUTES = 3;

  /**
   * The feature id for the '<em><b>Peak</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSPORT__PEAK = 4;

  /**
   * The feature id for the '<em><b>Non Peak</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSPORT__NON_PEAK = 5;

  /**
   * The number of structural features of the '<em>Transport</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSPORT_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.tfl.tfl.impl.RouteImpl <em>Route</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.tfl.tfl.impl.RouteImpl
   * @see org.xtext.example.tfl.tfl.impl.TflPackageImpl#getRoute()
   * @generated
   */
  int ROUTE = 3;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTE__START = 0;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTE__END = 1;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTE__DURATION = 2;

  /**
   * The number of structural features of the '<em>Route</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.tfl.tfl.impl.DisruptionImpl <em>Disruption</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.tfl.tfl.impl.DisruptionImpl
   * @see org.xtext.example.tfl.tfl.impl.TflPackageImpl#getDisruption()
   * @generated
   */
  int DISRUPTION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISRUPTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Transport</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISRUPTION__TRANSPORT = 1;

  /**
   * The feature id for the '<em><b>Stop</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISRUPTION__STOP = 2;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISRUPTION__DURATION = 3;

  /**
   * The number of structural features of the '<em>Disruption</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISRUPTION_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.tfl.tfl.TflSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see org.xtext.example.tfl.tfl.TflSystem
   * @generated
   */
  EClass getTflSystem();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.tfl.tfl.TflSystem#getStops <em>Stops</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stops</em>'.
   * @see org.xtext.example.tfl.tfl.TflSystem#getStops()
   * @see #getTflSystem()
   * @generated
   */
  EReference getTflSystem_Stops();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.tfl.tfl.TflSystem#getTransports <em>Transports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transports</em>'.
   * @see org.xtext.example.tfl.tfl.TflSystem#getTransports()
   * @see #getTflSystem()
   * @generated
   */
  EReference getTflSystem_Transports();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.tfl.tfl.TflSystem#getDisruptions <em>Disruptions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Disruptions</em>'.
   * @see org.xtext.example.tfl.tfl.TflSystem#getDisruptions()
   * @see #getTflSystem()
   * @generated
   */
  EReference getTflSystem_Disruptions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.tfl.tfl.Stop <em>Stop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stop</em>'.
   * @see org.xtext.example.tfl.tfl.Stop
   * @generated
   */
  EClass getStop();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tfl.tfl.Stop#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.tfl.tfl.Stop#getName()
   * @see #getStop()
   * @generated
   */
  EAttribute getStop_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.tfl.tfl.Transport <em>Transport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transport</em>'.
   * @see org.xtext.example.tfl.tfl.Transport
   * @generated
   */
  EClass getTransport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tfl.tfl.Transport#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.tfl.tfl.Transport#getName()
   * @see #getTransport()
   * @generated
   */
  EAttribute getTransport_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tfl.tfl.Transport#getCapacity <em>Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Capacity</em>'.
   * @see org.xtext.example.tfl.tfl.Transport#getCapacity()
   * @see #getTransport()
   * @generated
   */
  EAttribute getTransport_Capacity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tfl.tfl.Transport#getSpeed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed</em>'.
   * @see org.xtext.example.tfl.tfl.Transport#getSpeed()
   * @see #getTransport()
   * @generated
   */
  EAttribute getTransport_Speed();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.tfl.tfl.Transport#getRoutes <em>Routes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Routes</em>'.
   * @see org.xtext.example.tfl.tfl.Transport#getRoutes()
   * @see #getTransport()
   * @generated
   */
  EReference getTransport_Routes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tfl.tfl.Transport#getPeak <em>Peak</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Peak</em>'.
   * @see org.xtext.example.tfl.tfl.Transport#getPeak()
   * @see #getTransport()
   * @generated
   */
  EAttribute getTransport_Peak();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tfl.tfl.Transport#getNonPeak <em>Non Peak</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Non Peak</em>'.
   * @see org.xtext.example.tfl.tfl.Transport#getNonPeak()
   * @see #getTransport()
   * @generated
   */
  EAttribute getTransport_NonPeak();

  /**
   * Returns the meta object for class '{@link org.xtext.example.tfl.tfl.Route <em>Route</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Route</em>'.
   * @see org.xtext.example.tfl.tfl.Route
   * @generated
   */
  EClass getRoute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tfl.tfl.Route#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see org.xtext.example.tfl.tfl.Route#getStart()
   * @see #getRoute()
   * @generated
   */
  EAttribute getRoute_Start();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tfl.tfl.Route#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.xtext.example.tfl.tfl.Route#getEnd()
   * @see #getRoute()
   * @generated
   */
  EAttribute getRoute_End();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tfl.tfl.Route#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.example.tfl.tfl.Route#getDuration()
   * @see #getRoute()
   * @generated
   */
  EAttribute getRoute_Duration();

  /**
   * Returns the meta object for class '{@link org.xtext.example.tfl.tfl.Disruption <em>Disruption</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Disruption</em>'.
   * @see org.xtext.example.tfl.tfl.Disruption
   * @generated
   */
  EClass getDisruption();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tfl.tfl.Disruption#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.tfl.tfl.Disruption#getName()
   * @see #getDisruption()
   * @generated
   */
  EAttribute getDisruption_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.tfl.tfl.Disruption#getTransport <em>Transport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Transport</em>'.
   * @see org.xtext.example.tfl.tfl.Disruption#getTransport()
   * @see #getDisruption()
   * @generated
   */
  EReference getDisruption_Transport();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.tfl.tfl.Disruption#getStop <em>Stop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Stop</em>'.
   * @see org.xtext.example.tfl.tfl.Disruption#getStop()
   * @see #getDisruption()
   * @generated
   */
  EReference getDisruption_Stop();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tfl.tfl.Disruption#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.example.tfl.tfl.Disruption#getDuration()
   * @see #getDisruption()
   * @generated
   */
  EAttribute getDisruption_Duration();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TflFactory getTflFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.tfl.tfl.impl.TflSystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.tfl.tfl.impl.TflSystemImpl
     * @see org.xtext.example.tfl.tfl.impl.TflPackageImpl#getTflSystem()
     * @generated
     */
    EClass TFL_SYSTEM = eINSTANCE.getTflSystem();

    /**
     * The meta object literal for the '<em><b>Stops</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TFL_SYSTEM__STOPS = eINSTANCE.getTflSystem_Stops();

    /**
     * The meta object literal for the '<em><b>Transports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TFL_SYSTEM__TRANSPORTS = eINSTANCE.getTflSystem_Transports();

    /**
     * The meta object literal for the '<em><b>Disruptions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TFL_SYSTEM__DISRUPTIONS = eINSTANCE.getTflSystem_Disruptions();

    /**
     * The meta object literal for the '{@link org.xtext.example.tfl.tfl.impl.StopImpl <em>Stop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.tfl.tfl.impl.StopImpl
     * @see org.xtext.example.tfl.tfl.impl.TflPackageImpl#getStop()
     * @generated
     */
    EClass STOP = eINSTANCE.getStop();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STOP__NAME = eINSTANCE.getStop_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.tfl.tfl.impl.TransportImpl <em>Transport</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.tfl.tfl.impl.TransportImpl
     * @see org.xtext.example.tfl.tfl.impl.TflPackageImpl#getTransport()
     * @generated
     */
    EClass TRANSPORT = eINSTANCE.getTransport();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSPORT__NAME = eINSTANCE.getTransport_Name();

    /**
     * The meta object literal for the '<em><b>Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSPORT__CAPACITY = eINSTANCE.getTransport_Capacity();

    /**
     * The meta object literal for the '<em><b>Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSPORT__SPEED = eINSTANCE.getTransport_Speed();

    /**
     * The meta object literal for the '<em><b>Routes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSPORT__ROUTES = eINSTANCE.getTransport_Routes();

    /**
     * The meta object literal for the '<em><b>Peak</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSPORT__PEAK = eINSTANCE.getTransport_Peak();

    /**
     * The meta object literal for the '<em><b>Non Peak</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSPORT__NON_PEAK = eINSTANCE.getTransport_NonPeak();

    /**
     * The meta object literal for the '{@link org.xtext.example.tfl.tfl.impl.RouteImpl <em>Route</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.tfl.tfl.impl.RouteImpl
     * @see org.xtext.example.tfl.tfl.impl.TflPackageImpl#getRoute()
     * @generated
     */
    EClass ROUTE = eINSTANCE.getRoute();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROUTE__START = eINSTANCE.getRoute_Start();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROUTE__END = eINSTANCE.getRoute_End();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROUTE__DURATION = eINSTANCE.getRoute_Duration();

    /**
     * The meta object literal for the '{@link org.xtext.example.tfl.tfl.impl.DisruptionImpl <em>Disruption</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.tfl.tfl.impl.DisruptionImpl
     * @see org.xtext.example.tfl.tfl.impl.TflPackageImpl#getDisruption()
     * @generated
     */
    EClass DISRUPTION = eINSTANCE.getDisruption();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISRUPTION__NAME = eINSTANCE.getDisruption_Name();

    /**
     * The meta object literal for the '<em><b>Transport</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISRUPTION__TRANSPORT = eINSTANCE.getDisruption_Transport();

    /**
     * The meta object literal for the '<em><b>Stop</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISRUPTION__STOP = eINSTANCE.getDisruption_Stop();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISRUPTION__DURATION = eINSTANCE.getDisruption_Duration();

  }

} //TflPackage
