/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.tfl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tfl.tfl.TflSystem#getStops <em>Stops</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.TflSystem#getTransports <em>Transports</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.TflSystem#getDisruptions <em>Disruptions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.tfl.tfl.TflPackage#getTflSystem()
 * @model
 * @generated
 */
public interface TflSystem extends EObject
{
  /**
   * Returns the value of the '<em><b>Stops</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.tfl.tfl.Stop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stops</em>' containment reference list.
   * @see org.xtext.example.tfl.tfl.TflPackage#getTflSystem_Stops()
   * @model containment="true"
   * @generated
   */
  EList<Stop> getStops();

  /**
   * Returns the value of the '<em><b>Transports</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.tfl.tfl.Transport}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transports</em>' containment reference list.
   * @see org.xtext.example.tfl.tfl.TflPackage#getTflSystem_Transports()
   * @model containment="true"
   * @generated
   */
  EList<Transport> getTransports();

  /**
   * Returns the value of the '<em><b>Disruptions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.tfl.tfl.Disruption}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Disruptions</em>' containment reference list.
   * @see org.xtext.example.tfl.tfl.TflPackage#getTflSystem_Disruptions()
   * @model containment="true"
   * @generated
   */
  EList<Disruption> getDisruptions();

} // TflSystem
