/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.tfl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transport</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tfl.tfl.Transport#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.Transport#getCapacity <em>Capacity</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.Transport#getSpeed <em>Speed</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.Transport#getRoutes <em>Routes</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.Transport#getPeak <em>Peak</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.Transport#getNonPeak <em>Non Peak</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.tfl.tfl.TflPackage#getTransport()
 * @model
 * @generated
 */
public interface Transport extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.tfl.tfl.TflPackage#getTransport_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.tfl.tfl.Transport#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capacity</em>' attribute.
   * @see #setCapacity(int)
   * @see org.xtext.example.tfl.tfl.TflPackage#getTransport_Capacity()
   * @model
   * @generated
   */
  int getCapacity();

  /**
   * Sets the value of the '{@link org.xtext.example.tfl.tfl.Transport#getCapacity <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Capacity</em>' attribute.
   * @see #getCapacity()
   * @generated
   */
  void setCapacity(int value);

  /**
   * Returns the value of the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed</em>' attribute.
   * @see #setSpeed(float)
   * @see org.xtext.example.tfl.tfl.TflPackage#getTransport_Speed()
   * @model
   * @generated
   */
  float getSpeed();

  /**
   * Sets the value of the '{@link org.xtext.example.tfl.tfl.Transport#getSpeed <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speed</em>' attribute.
   * @see #getSpeed()
   * @generated
   */
  void setSpeed(float value);

  /**
   * Returns the value of the '<em><b>Routes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.tfl.tfl.Route}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Routes</em>' containment reference list.
   * @see org.xtext.example.tfl.tfl.TflPackage#getTransport_Routes()
   * @model containment="true"
   * @generated
   */
  EList<Route> getRoutes();

  /**
   * Returns the value of the '<em><b>Peak</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Peak</em>' attribute.
   * @see #setPeak(int)
   * @see org.xtext.example.tfl.tfl.TflPackage#getTransport_Peak()
   * @model
   * @generated
   */
  int getPeak();

  /**
   * Sets the value of the '{@link org.xtext.example.tfl.tfl.Transport#getPeak <em>Peak</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Peak</em>' attribute.
   * @see #getPeak()
   * @generated
   */
  void setPeak(int value);

  /**
   * Returns the value of the '<em><b>Non Peak</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Non Peak</em>' attribute.
   * @see #setNonPeak(int)
   * @see org.xtext.example.tfl.tfl.TflPackage#getTransport_NonPeak()
   * @model
   * @generated
   */
  int getNonPeak();

  /**
   * Sets the value of the '{@link org.xtext.example.tfl.tfl.Transport#getNonPeak <em>Non Peak</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Non Peak</em>' attribute.
   * @see #getNonPeak()
   * @generated
   */
  void setNonPeak(int value);

} // Transport
