/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.generator;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import org.xtext.example.tfl.tfl.Disruption;
import org.xtext.example.tfl.tfl.Route;
import org.xtext.example.tfl.tfl.TflSystem;
import org.xtext.example.tfl.tfl.Transport;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class TflGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IterableExtensions.<EObject>head(resource.getContents());
    final TflSystem model = ((TflSystem) _head);
    final String className = this.deriveClassNameFor(resource);
    fsa.generateFile((className + ".java"), this.doGenerateClass(model, className));
  }

  public String deriveClassNameFor(final Resource resource) {
    String _xblockexpression = null;
    {
      final String origName = resource.getURI().lastSegment();
      String _firstUpper = StringExtensions.toFirstUpper(origName.substring(0, origName.indexOf(".")));
      _xblockexpression = (_firstUpper + "Tfl");
    }
    return _xblockexpression;
  }

  public CharSequence doGenerateClass(final TflSystem model, final String className) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("import java.util.*;");
    _builder.newLine();
    _builder.append("import org.xtext.example.tfl.library.*;");
    _builder.newLine();
    _builder.append("import org.xtext.example.tfl.library.TransportScheduler.Route;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(className);
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public static void main(String[] args) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("TransportScheduler manager = new TransportScheduler();");
    _builder.newLine();
    _builder.newLine();
    {
      EList<Transport> _transports = model.getTransports();
      for(final Transport transport : _transports) {
        _builder.append("        ");
        _builder.append("manager.addTransport(\"");
        String _name = transport.getName();
        _builder.append(_name, "        ");
        _builder.append("\", ");
        int _capacity = transport.getCapacity();
        _builder.append(_capacity, "        ");
        _builder.append(", ");
        float _speed = transport.getSpeed();
        _builder.append(_speed, "        ");
        _builder.append(", Arrays.asList(");
        _builder.newLineIfNotEmpty();
        {
          EList<Route> _routes = transport.getRoutes();
          boolean _hasElements = false;
          for(final Route route : _routes) {
            if (!_hasElements) {
              _hasElements = true;
            } else {
              _builder.appendImmediate(",", "            ");
            }
            _builder.append("        ");
            _builder.append("    ");
            _builder.append("new Route<>(\"");
            String _start = route.getStart();
            _builder.append(_start, "            ");
            _builder.append("\",\"");
            String _end = route.getEnd();
            _builder.append(_end, "            ");
            _builder.append("\", ");
            int _duration = route.getDuration();
            _builder.append(_duration, "            ");
            _builder.append(")");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("        ");
        _builder.append("), ");
        int _peak = transport.getPeak();
        _builder.append(_peak, "        ");
        _builder.append(", ");
        int _nonPeak = transport.getNonPeak();
        _builder.append(_nonPeak, "        ");
        _builder.append(");");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    {
      EList<Disruption> _disruptions = model.getDisruptions();
      for(final Disruption disruption : _disruptions) {
        _builder.append("        ");
        _builder.append("manager.addDisruption(\"");
        String _name_1 = disruption.getTransport().getName();
        _builder.append(_name_1, "        ");
        _builder.append("\", \"");
        String _name_2 = disruption.getStop().getName();
        _builder.append(_name_2, "        ");
        _builder.append("\", ");
        int _duration_1 = disruption.getDuration();
        _builder.append(_duration_1, "        ");
        _builder.append(");");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    _builder.append("        ");
    _builder.append("manager.generateSchedule();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("manager.calculateFare();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
