/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.validation;

import org.xtext.example.tfl.tfl.Stop;
import org.eclipse.xtext.validation.Check
import org.xtext.example.tfl.tfl.TflPackage
import org.xtext.example.tfl.tfl.TflSystem
import org.eclipse.emf.common.util.EList
import org.xtext.example.tfl.tfl.Transport
import org.xtext.example.tfl.tfl.Disruption

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TflValidator extends AbstractTflValidator {
	
	public static final String INVALID_STOP_NAME = "invalidStopName";
	public static final String UNUSED_STOP = "unusedStop";
	public static final String DUPLICATE_DISRUPTION = "duplicateDisruption";
	
	@Check
	def checkStopName(Stop stop){
		if (Character.isLowerCase(stop.name.charAt(0))) {
			warning('Stop name should start with an upper-case character', stop,
				TflPackage.Literals.STOP__NAME, INVALID_STOP_NAME)
		}
	}
	
	@Check(NORMAL)
	def checkIfStopIsUsed(TflSystem system) {
    	for (stop : system.stops) {
        	if (!isStopReferenced(stop, system.transports, system.disruptions)) {
            	warning("This stop is unused", stop,
                	TflPackage.Literals.STOP__NAME, UNUSED_STOP)
        	}
    	}
	}

	def boolean isStopReferenced(Stop stop, EList<Transport> transports, EList<Disruption> disruptions) {
    	for (transport : transports) {
        	for (route : transport.routes) {
            	if (route.start.equals(stop.name) || route.end.equals(stop.name)) {
                	return true // Stop is used in a transport route
            	}
        	}
    	}
    
    	for (disruption : disruptions) {
        	if (disruption.stop == stop) {
            	return true // Stop is affected by a disruption
        	}
    	}
    
    	return false // Stop is unused
	}	
}
