/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.tfl.parser.antlr.internal.InternalTflParser;
import org.xtext.example.tfl.services.TflGrammarAccess;

public class TflParser extends AbstractAntlrParser {

	@Inject
	private TflGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTflParser createParser(XtextTokenStream stream) {
		return new InternalTflParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TflSystem";
	}

	public TflGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TflGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
