/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.tfl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.tfl.tfl.Disruption;
import org.xtext.example.tfl.tfl.Stop;
import org.xtext.example.tfl.tfl.TflPackage;
import org.xtext.example.tfl.tfl.Transport;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Disruption</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.DisruptionImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.DisruptionImpl#getTransport <em>Transport</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.DisruptionImpl#getStop <em>Stop</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.DisruptionImpl#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DisruptionImpl extends MinimalEObjectImpl.Container implements Disruption
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTransport() <em>Transport</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTransport()
   * @generated
   * @ordered
   */
  protected Transport transport;

  /**
   * The cached value of the '{@link #getStop() <em>Stop</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStop()
   * @generated
   * @ordered
   */
  protected Stop stop;

  /**
   * The default value of the '{@link #getDuration() <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDuration()
   * @generated
   * @ordered
   */
  protected static final int DURATION_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDuration() <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDuration()
   * @generated
   * @ordered
   */
  protected int duration = DURATION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DisruptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TflPackage.Literals.DISRUPTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TflPackage.DISRUPTION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Transport getTransport()
  {
    if (transport != null && transport.eIsProxy())
    {
      InternalEObject oldTransport = (InternalEObject)transport;
      transport = (Transport)eResolveProxy(oldTransport);
      if (transport != oldTransport)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, TflPackage.DISRUPTION__TRANSPORT, oldTransport, transport));
      }
    }
    return transport;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Transport basicGetTransport()
  {
    return transport;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTransport(Transport newTransport)
  {
    Transport oldTransport = transport;
    transport = newTransport;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TflPackage.DISRUPTION__TRANSPORT, oldTransport, transport));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Stop getStop()
  {
    if (stop != null && stop.eIsProxy())
    {
      InternalEObject oldStop = (InternalEObject)stop;
      stop = (Stop)eResolveProxy(oldStop);
      if (stop != oldStop)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, TflPackage.DISRUPTION__STOP, oldStop, stop));
      }
    }
    return stop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Stop basicGetStop()
  {
    return stop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStop(Stop newStop)
  {
    Stop oldStop = stop;
    stop = newStop;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TflPackage.DISRUPTION__STOP, oldStop, stop));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getDuration()
  {
    return duration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDuration(int newDuration)
  {
    int oldDuration = duration;
    duration = newDuration;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TflPackage.DISRUPTION__DURATION, oldDuration, duration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TflPackage.DISRUPTION__NAME:
        return getName();
      case TflPackage.DISRUPTION__TRANSPORT:
        if (resolve) return getTransport();
        return basicGetTransport();
      case TflPackage.DISRUPTION__STOP:
        if (resolve) return getStop();
        return basicGetStop();
      case TflPackage.DISRUPTION__DURATION:
        return getDuration();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TflPackage.DISRUPTION__NAME:
        setName((String)newValue);
        return;
      case TflPackage.DISRUPTION__TRANSPORT:
        setTransport((Transport)newValue);
        return;
      case TflPackage.DISRUPTION__STOP:
        setStop((Stop)newValue);
        return;
      case TflPackage.DISRUPTION__DURATION:
        setDuration((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TflPackage.DISRUPTION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case TflPackage.DISRUPTION__TRANSPORT:
        setTransport((Transport)null);
        return;
      case TflPackage.DISRUPTION__STOP:
        setStop((Stop)null);
        return;
      case TflPackage.DISRUPTION__DURATION:
        setDuration(DURATION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TflPackage.DISRUPTION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case TflPackage.DISRUPTION__TRANSPORT:
        return transport != null;
      case TflPackage.DISRUPTION__STOP:
        return stop != null;
      case TflPackage.DISRUPTION__DURATION:
        return duration != DURATION_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", duration: ");
    result.append(duration);
    result.append(')');
    return result.toString();
  }

} //DisruptionImpl
