/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.tfl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.tfl.tfl.Disruption;
import org.xtext.example.tfl.tfl.Stop;
import org.xtext.example.tfl.tfl.TflPackage;
import org.xtext.example.tfl.tfl.TflSystem;
import org.xtext.example.tfl.tfl.Transport;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.TflSystemImpl#getStops <em>Stops</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.TflSystemImpl#getTransports <em>Transports</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.TflSystemImpl#getDisruptions <em>Disruptions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TflSystemImpl extends MinimalEObjectImpl.Container implements TflSystem
{
  /**
   * The cached value of the '{@link #getStops() <em>Stops</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStops()
   * @generated
   * @ordered
   */
  protected EList<Stop> stops;

  /**
   * The cached value of the '{@link #getTransports() <em>Transports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTransports()
   * @generated
   * @ordered
   */
  protected EList<Transport> transports;

  /**
   * The cached value of the '{@link #getDisruptions() <em>Disruptions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisruptions()
   * @generated
   * @ordered
   */
  protected EList<Disruption> disruptions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TflSystemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TflPackage.Literals.TFL_SYSTEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Stop> getStops()
  {
    if (stops == null)
    {
      stops = new EObjectContainmentEList<Stop>(Stop.class, this, TflPackage.TFL_SYSTEM__STOPS);
    }
    return stops;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Transport> getTransports()
  {
    if (transports == null)
    {
      transports = new EObjectContainmentEList<Transport>(Transport.class, this, TflPackage.TFL_SYSTEM__TRANSPORTS);
    }
    return transports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Disruption> getDisruptions()
  {
    if (disruptions == null)
    {
      disruptions = new EObjectContainmentEList<Disruption>(Disruption.class, this, TflPackage.TFL_SYSTEM__DISRUPTIONS);
    }
    return disruptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TflPackage.TFL_SYSTEM__STOPS:
        return ((InternalEList<?>)getStops()).basicRemove(otherEnd, msgs);
      case TflPackage.TFL_SYSTEM__TRANSPORTS:
        return ((InternalEList<?>)getTransports()).basicRemove(otherEnd, msgs);
      case TflPackage.TFL_SYSTEM__DISRUPTIONS:
        return ((InternalEList<?>)getDisruptions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TflPackage.TFL_SYSTEM__STOPS:
        return getStops();
      case TflPackage.TFL_SYSTEM__TRANSPORTS:
        return getTransports();
      case TflPackage.TFL_SYSTEM__DISRUPTIONS:
        return getDisruptions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TflPackage.TFL_SYSTEM__STOPS:
        getStops().clear();
        getStops().addAll((Collection<? extends Stop>)newValue);
        return;
      case TflPackage.TFL_SYSTEM__TRANSPORTS:
        getTransports().clear();
        getTransports().addAll((Collection<? extends Transport>)newValue);
        return;
      case TflPackage.TFL_SYSTEM__DISRUPTIONS:
        getDisruptions().clear();
        getDisruptions().addAll((Collection<? extends Disruption>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TflPackage.TFL_SYSTEM__STOPS:
        getStops().clear();
        return;
      case TflPackage.TFL_SYSTEM__TRANSPORTS:
        getTransports().clear();
        return;
      case TflPackage.TFL_SYSTEM__DISRUPTIONS:
        getDisruptions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TflPackage.TFL_SYSTEM__STOPS:
        return stops != null && !stops.isEmpty();
      case TflPackage.TFL_SYSTEM__TRANSPORTS:
        return transports != null && !transports.isEmpty();
      case TflPackage.TFL_SYSTEM__DISRUPTIONS:
        return disruptions != null && !disruptions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //TflSystemImpl
