/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.tfl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.tfl.tfl.Route;
import org.xtext.example.tfl.tfl.TflPackage;
import org.xtext.example.tfl.tfl.Transport;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Transport</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.TransportImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.TransportImpl#getCapacity <em>Capacity</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.TransportImpl#getSpeed <em>Speed</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.TransportImpl#getRoutes <em>Routes</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.TransportImpl#getPeak <em>Peak</em>}</li>
 *   <li>{@link org.xtext.example.tfl.tfl.impl.TransportImpl#getNonPeak <em>Non Peak</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TransportImpl extends MinimalEObjectImpl.Container implements Transport
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getCapacity() <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapacity()
   * @generated
   * @ordered
   */
  protected static final int CAPACITY_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCapacity() <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapacity()
   * @generated
   * @ordered
   */
  protected int capacity = CAPACITY_EDEFAULT;

  /**
   * The default value of the '{@link #getSpeed() <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeed()
   * @generated
   * @ordered
   */
  protected static final float SPEED_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getSpeed() <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeed()
   * @generated
   * @ordered
   */
  protected float speed = SPEED_EDEFAULT;

  /**
   * The cached value of the '{@link #getRoutes() <em>Routes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoutes()
   * @generated
   * @ordered
   */
  protected EList<Route> routes;

  /**
   * The default value of the '{@link #getPeak() <em>Peak</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPeak()
   * @generated
   * @ordered
   */
  protected static final int PEAK_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPeak() <em>Peak</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPeak()
   * @generated
   * @ordered
   */
  protected int peak = PEAK_EDEFAULT;

  /**
   * The default value of the '{@link #getNonPeak() <em>Non Peak</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNonPeak()
   * @generated
   * @ordered
   */
  protected static final int NON_PEAK_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNonPeak() <em>Non Peak</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNonPeak()
   * @generated
   * @ordered
   */
  protected int nonPeak = NON_PEAK_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TransportImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TflPackage.Literals.TRANSPORT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TflPackage.TRANSPORT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getCapacity()
  {
    return capacity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCapacity(int newCapacity)
  {
    int oldCapacity = capacity;
    capacity = newCapacity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TflPackage.TRANSPORT__CAPACITY, oldCapacity, capacity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public float getSpeed()
  {
    return speed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpeed(float newSpeed)
  {
    float oldSpeed = speed;
    speed = newSpeed;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TflPackage.TRANSPORT__SPEED, oldSpeed, speed));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Route> getRoutes()
  {
    if (routes == null)
    {
      routes = new EObjectContainmentEList<Route>(Route.class, this, TflPackage.TRANSPORT__ROUTES);
    }
    return routes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPeak()
  {
    return peak;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPeak(int newPeak)
  {
    int oldPeak = peak;
    peak = newPeak;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TflPackage.TRANSPORT__PEAK, oldPeak, peak));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNonPeak()
  {
    return nonPeak;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNonPeak(int newNonPeak)
  {
    int oldNonPeak = nonPeak;
    nonPeak = newNonPeak;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TflPackage.TRANSPORT__NON_PEAK, oldNonPeak, nonPeak));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TflPackage.TRANSPORT__ROUTES:
        return ((InternalEList<?>)getRoutes()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TflPackage.TRANSPORT__NAME:
        return getName();
      case TflPackage.TRANSPORT__CAPACITY:
        return getCapacity();
      case TflPackage.TRANSPORT__SPEED:
        return getSpeed();
      case TflPackage.TRANSPORT__ROUTES:
        return getRoutes();
      case TflPackage.TRANSPORT__PEAK:
        return getPeak();
      case TflPackage.TRANSPORT__NON_PEAK:
        return getNonPeak();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TflPackage.TRANSPORT__NAME:
        setName((String)newValue);
        return;
      case TflPackage.TRANSPORT__CAPACITY:
        setCapacity((Integer)newValue);
        return;
      case TflPackage.TRANSPORT__SPEED:
        setSpeed((Float)newValue);
        return;
      case TflPackage.TRANSPORT__ROUTES:
        getRoutes().clear();
        getRoutes().addAll((Collection<? extends Route>)newValue);
        return;
      case TflPackage.TRANSPORT__PEAK:
        setPeak((Integer)newValue);
        return;
      case TflPackage.TRANSPORT__NON_PEAK:
        setNonPeak((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TflPackage.TRANSPORT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case TflPackage.TRANSPORT__CAPACITY:
        setCapacity(CAPACITY_EDEFAULT);
        return;
      case TflPackage.TRANSPORT__SPEED:
        setSpeed(SPEED_EDEFAULT);
        return;
      case TflPackage.TRANSPORT__ROUTES:
        getRoutes().clear();
        return;
      case TflPackage.TRANSPORT__PEAK:
        setPeak(PEAK_EDEFAULT);
        return;
      case TflPackage.TRANSPORT__NON_PEAK:
        setNonPeak(NON_PEAK_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TflPackage.TRANSPORT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case TflPackage.TRANSPORT__CAPACITY:
        return capacity != CAPACITY_EDEFAULT;
      case TflPackage.TRANSPORT__SPEED:
        return speed != SPEED_EDEFAULT;
      case TflPackage.TRANSPORT__ROUTES:
        return routes != null && !routes.isEmpty();
      case TflPackage.TRANSPORT__PEAK:
        return peak != PEAK_EDEFAULT;
      case TflPackage.TRANSPORT__NON_PEAK:
        return nonPeak != NON_PEAK_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", capacity: ");
    result.append(capacity);
    result.append(", speed: ");
    result.append(speed);
    result.append(", peak: ");
    result.append(peak);
    result.append(", nonPeak: ");
    result.append(nonPeak);
    result.append(')');
    return result.toString();
  }

} //TransportImpl
