/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix
import org.xtext.example.tfl.validation.TflValidator
import org.eclipse.xtext.validation.Issue
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
class TflQuickfixProvider extends DefaultQuickfixProvider {

	@Fix(TflValidator.INVALID_STOP_NAME)
	def capitalizeName(Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, 'Capitalise stop name', 'Capitalise the stop name.', 'upcase.png') [
			context |
			val xtextDocument = context.xtextDocument
			val firstLetter = xtextDocument.get(issue.offset, 1) // Get the first letter
			xtextDocument.replace(issue.offset, 1, firstLetter.toUpperCase) // Replace it with its upper case value
		]
	}
	
	@Fix(TflValidator.UNUSED_STOP)
	def removeUnusedStop(Issue issue, IssueResolutionAcceptor acceptor) {
    	acceptor.accept(issue, "Remove this stop", "Removes the entire line containing the unused stop.", "") [
        	context |
        	val xtextDocument = context.xtextDocument
        
        	// Get the entire line where the issue occurs
        	val text = xtextDocument.get()
        	val offset = issue.offset
        	val length = issue.length
        
        	// Find start and end of the line
        	val lineStart = text.lastIndexOf("\n", offset - 1) + 1  // Move to start of line
        	val lineEnd = text.indexOf("\n", offset + length)  // Find next newline
        	val removeEnd = if (lineEnd != -1) lineEnd + 1 else text.length  // Include newline in deletion

        	// Remove the full line
        	xtextDocument.replace(lineStart, removeEnd - lineStart, "")
    	]
	}
}
