/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTflScopeProvider extends DelegatingScopeProvider {
}
