/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.tfl.services.TflGrammarAccess;
import org.xtext.example.tfl.tfl.Disruption;
import org.xtext.example.tfl.tfl.Route;
import org.xtext.example.tfl.tfl.Stop;
import org.xtext.example.tfl.tfl.TflPackage;
import org.xtext.example.tfl.tfl.TflSystem;
import org.xtext.example.tfl.tfl.Transport;

@SuppressWarnings("all")
public class TflSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private TflGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == TflPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TflPackage.DISRUPTION:
				sequence_Disruption(context, (Disruption) semanticObject); 
				return; 
			case TflPackage.ROUTE:
				sequence_Route(context, (Route) semanticObject); 
				return; 
			case TflPackage.STOP:
				sequence_Stop(context, (Stop) semanticObject); 
				return; 
			case TflPackage.TFL_SYSTEM:
				sequence_TflSystem(context, (TflSystem) semanticObject); 
				return; 
			case TflPackage.TRANSPORT:
				sequence_Transport(context, (Transport) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Disruption returns Disruption
	 *
	 * Constraint:
	 *     (name=ID transport=[Transport|ID] stop=[Stop|ID] duration=INT)
	 * </pre>
	 */
	protected void sequence_Disruption(ISerializationContext context, Disruption semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TflPackage.Literals.DISRUPTION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TflPackage.Literals.DISRUPTION__NAME));
			if (transientValues.isValueTransient(semanticObject, TflPackage.Literals.DISRUPTION__TRANSPORT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TflPackage.Literals.DISRUPTION__TRANSPORT));
			if (transientValues.isValueTransient(semanticObject, TflPackage.Literals.DISRUPTION__STOP) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TflPackage.Literals.DISRUPTION__STOP));
			if (transientValues.isValueTransient(semanticObject, TflPackage.Literals.DISRUPTION__DURATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TflPackage.Literals.DISRUPTION__DURATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDisruptionAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getDisruptionAccess().getTransportTransportIDTerminalRuleCall_3_0_1(), semanticObject.eGet(TflPackage.Literals.DISRUPTION__TRANSPORT, false));
		feeder.accept(grammarAccess.getDisruptionAccess().getStopStopIDTerminalRuleCall_5_0_1(), semanticObject.eGet(TflPackage.Literals.DISRUPTION__STOP, false));
		feeder.accept(grammarAccess.getDisruptionAccess().getDurationINTTerminalRuleCall_7_0(), semanticObject.getDuration());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Route returns Route
	 *
	 * Constraint:
	 *     (start=ID end=ID duration=INT)
	 * </pre>
	 */
	protected void sequence_Route(ISerializationContext context, Route semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TflPackage.Literals.ROUTE__START) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TflPackage.Literals.ROUTE__START));
			if (transientValues.isValueTransient(semanticObject, TflPackage.Literals.ROUTE__END) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TflPackage.Literals.ROUTE__END));
			if (transientValues.isValueTransient(semanticObject, TflPackage.Literals.ROUTE__DURATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TflPackage.Literals.ROUTE__DURATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRouteAccess().getStartIDTerminalRuleCall_0_0(), semanticObject.getStart());
		feeder.accept(grammarAccess.getRouteAccess().getEndIDTerminalRuleCall_2_0(), semanticObject.getEnd());
		feeder.accept(grammarAccess.getRouteAccess().getDurationINTTerminalRuleCall_4_0(), semanticObject.getDuration());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Stop returns Stop
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_Stop(ISerializationContext context, Stop semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TflPackage.Literals.STOP__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TflPackage.Literals.STOP__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStopAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TflSystem returns TflSystem
	 *
	 * Constraint:
	 *     ((stops+=Stop* transports+=Transport+ disruptions+=Disruption+) | (stops+=Stop* disruptions+=Disruption+) | disruptions+=Disruption+)?
	 * </pre>
	 */
	protected void sequence_TflSystem(ISerializationContext context, TflSystem semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Transport returns Transport
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         capacity=INT 
	 *         speed=REAL 
	 *         routes+=Route* 
	 *         peak=INT 
	 *         nonPeak=INT
	 *     )
	 * </pre>
	 */
	protected void sequence_Transport(ISerializationContext context, Transport semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
