/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.tfl.ui.quickfix;

import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.xtext.example.tfl.validation.TflValidator;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class TflQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(TflValidator.INVALID_STOP_NAME)
  public void capitalizeName(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = (IModificationContext context) -> {
      final IXtextDocument xtextDocument = context.getXtextDocument();
      final String firstLetter = xtextDocument.get((issue.getOffset()).intValue(), 1);
      xtextDocument.replace((issue.getOffset()).intValue(), 1, firstLetter.toUpperCase());
    };
    acceptor.accept(issue, "Capitalise stop name", "Capitalise the stop name.", "upcase.png", _function);
  }

  @Fix(TflValidator.UNUSED_STOP)
  public void removeUnusedStop(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = (IModificationContext context) -> {
      final IXtextDocument xtextDocument = context.getXtextDocument();
      final String text = xtextDocument.get();
      final Integer offset = issue.getOffset();
      final Integer length = issue.getLength();
      int _lastIndexOf = text.lastIndexOf("\n", ((offset).intValue() - 1));
      final int lineStart = (_lastIndexOf + 1);
      final int lineEnd = text.indexOf("\n", ((offset).intValue() + (length).intValue()));
      int _xifexpression = (int) 0;
      if ((lineEnd != (-1))) {
        _xifexpression = (lineEnd + 1);
      } else {
        _xifexpression = text.length();
      }
      final int removeEnd = _xifexpression;
      xtextDocument.replace(lineStart, (removeEnd - lineStart), "");
    };
    acceptor.accept(issue, "Remove this stop", "Removes the entire line containing the unused stop.", "", _function);
  }
}
